[project]
name = "voice-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.117.1",
    "pipecat-ai[deepgram,openai,silero,webrtc]>=0.0.86",
    "uvicorn>=0.37.0",
]
